# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messenger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messenger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\x12\tmessenger\"9\n\x07Message\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\"\n\x0e\x43onnectRequest\x12\x10\n\x08username\x18\x01 \x01(\t2L\n\x10MessengerService\x12\x38\n\nChatStream\x12\x12.messenger.Message\x1a\x12.messenger.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=30
  _globals['_MESSAGE']._serialized_end=87
  _globals['_CONNECTREQUEST']._serialized_start=89
  _globals['_CONNECTREQUEST']._serialized_end=123
  _globals['_MESSENGERSERVICE']._serialized_start=125
  _globals['_MESSENGERSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
