worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    proxy_cache_path /var/cache/nginx/history_cache keys_zone=history_cache_zone:10m inactive=60s;

    upstream api_backend {
        server app1:8000;
        server app2:8000;
    }

    server {
        listen 80;

        location = /api/history {
            proxy_pass http://api_backend;
            proxy_cache history_cache_zone;
            proxy_cache_methods GET;
            proxy_cache_valid 200 30s;
            add_header X-Cache-Status $upstream_cache_status;
        }

        location / {
            proxy_pass http://api_backend;
        }
    }
}
